// auth
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// home
export const GET_ALL_CONSTRUCTION = "GET_ALL_CONSTRUCTION";
export const GET_ALL_CONSTRUCTION_SUCCESS = "GET_ALL_CONSTRUCTION_SUCCESS";
export const GET_ALL_CONSTRUCTION_FAIL = "GET_ALL_CONSTRUCTION_FAIL";

export const GET_CONSTRUCTION = "GET_CONSTRUCTION";
export const GET_CONSTRUCTION_SUCCESS = "GET_CONSTRUCTION_SUCCESS";
export const GET_CONSTRUCTION_FAIL = "GET_CONSTRUCTION_FAIL";

export const POST_CONSTRUCTION = "POST_CONSTRUCTION";
export const POST_CONSTRUCTION_SUCCESS = "POST_CONSTRUCTION_SUCCESS";
export const POST_CONSTRUCTION_FAIL = "POST_CONSTRUCTION_FAIL";

export const PUT_CONSTRUCTION = "PUT_CONSTRUCTION";
export const PUT_CONSTRUCTION_SUCCESS = "PUT_CONSTRUCTION_SUCCESS";
export const PUT_CONSTRUCTION_FAIL = "PUT_CONSTRUCTION_FAIL";

export const DEL_CONSTRUCTION = "DEL_CONSTRUCTION";
export const DEL_CONSTRUCTION_SUCCESS = "DEL_CONSTRUCTION_SUCCESS";
export const DEL_CONSTRUCTION_FAIL = "DEL_CONSTRUCTION_FAIL";

// products
export const GET_TYPE_PARAMETER_CONSTRUCTION =
  "GET_TYPE_PARAMETER_CONSTRUCTION";
export const GET_TYPE_PARAMETER_CONSTRUCTION_SUCCESS =
  "GET_TYPE_PARAMETER_CONSTRUCTION_CUCCESS";
export const GET_TYPE_PARAMETER_CONSTRUCTION_FAIL =
  "GET_TYPE_PARAMETER_CONSTRUCTION_FAIL";

export const GET_PARAMETER_CONSTRUCTION = "GET_PARAMETER_CONSTRUCTION";
export const GET_PARAMETER_CONSTRUCTION_SUCCESS =
  "GET_PARAMETER_CONSTRUCTION_CUCCESS";
export const GET_PARAMETER_CONSTRUCTION_FAIL =
  "GET_PARAMETER_CONSTRUCTION_FAIL";

export const POST_PARAMETER_CONSTRUCTION = "POST_PARAMETER_CONSTRUCTION";
export const POST_PARAMETER_CONSTRUCTION_SUCCESS =
  "POST_PARAMETER_CONSTRUCTION_CUCCESS";
export const POST_PARAMETER_CONSTRUCTION_FAIL =
  "POST_PARAMETER_CONSTRUCTION_FAIL";

export const PUT_PARAMETER_CONSTRUCTION = "PUT_PARAMETER_CONSTRUCTION";
export const PUT_PARAMETER_CONSTRUCTION_SUCCESS =
  "PUT_PARAMETER_CONSTRUCTION_CUCCESS";
export const PUT_PARAMETER_CONSTRUCTION_FAIL =
  "PUT_PARAMETER_CONSTRUCTION_FAIL";

export const DEL_PARAMETER_CONSTRUCTION = "DEL_PARAMETER_CONSTRUCTION";
export const DEL_PARAMETER_CONSTRUCTION_SUCCESS =
  "DEL_PARAMETER_CONSTRUCTION_CUCCESS";
export const DEL_PARAMETER_CONSTRUCTION_FAIL =
  "DEL_PARAMETER_CONSTRUCTION_FAIL";

export const FIND_PARAMETER_CONSTRUCTION = "FIND_PARAMETER_CONSTRUCTION";
export const FIND_PARAMETER_CONSTRUCTION_SUCCESS =
  "FIND_PARAMETER_CONSTRUCTION_CUCCESS";
export const FIND_PARAMETER_CONSTRUCTION_FAIL =
  "FIND_PARAMETER_CONSTRUCTION_FAIL";

// Order
export const GET_ALL_PARAMETER = "GET_ALL_PARAMETER";
export const GET_ALL_PARAMETER_SUCCESS = "GET_ALL_PARAMETER_CUCCESS";
export const GET_ALL_PARAMETER_FAIL = "GET_ALL_PARAMETER_FAIL";

export const GET_STEEL_PART = "GET_STEEL_PART";
export const GET_STEEL_PART_SUCCESS = "GET_STEEL_PART_CUCCESS";
export const GET_STEEL_PART_FAIL = "GET_STEEL_PART_FAIL";

export const GET_INIT_TYPE = "GET_INIT_TYPE";
export const GET_INIT_TYPE_SUCCESS = "GET_INIT_TYPE_CUCCESS";
export const GET_INIT_TYPE_FAIL = "GET_INIT_TYPE_FAIL";

export const GET_INIT_MATERIAL = "GET_INIT_MATERIAL";
export const GET_INIT_MATERIAL_SUCCESS = "GET_INIT_MATERIAL_CUCCESS";
export const GET_INIT_MATERIAL_FAIL = "GET_INIT_MATERIAL_FAIL";

export const GET_INIT_SIZE = "GET_INIT_SIZE";
export const GET_INIT_SIZE_SUCCESS = "GET_INIT_SIZE_CUCCESS";
export const GET_INIT_SIZE_FAIL = "GET_INIT_SIZE_FAIL";

export const GET_INIT_MACHINED = "GET_INIT_MACHINED";
export const GET_INIT_MACHINED_SUCCESS = "GET_INIT_MACHINED_CUCCESS";
export const GET_INIT_MACHINED_FAIL = "GET_INIT_MACHINED_FAIL";

export const GET_INIT_PAINT_TYPE = "GET_INIT_PAINT_TYPE";
export const GET_INIT_PAINT_TYPE_SUCCESS = "GET_INIT_PAINT_TYPE_CUCCESS";
export const GET_INIT_PAINT_TYPE_FAIL = "GET_INIT_PAINT_TYPE_FAIL";

export const GET_INIT_PRODUCER_SEARCH = "GET_INIT_PRODUCER_SEARCH";
export const GET_INIT_PRODUCER_SEARCH_SUCCESS =
  "GET_INIT_PRODUCER_SEARCH_CUCCESS";
export const GET_INIT_PRODUCER_SEARCH_FAIL = "GET_INIT_PRODUCER_SEARCH_FAIL";

export const GET_LIST_ORDER_STEEL_SHAPE = "GET_LIST_ORDER_STEEL_SHAPE";
export const GET_LIST_ORDER_STEEL_SHAPE_SUCCESS =
  "GET_LIST_ORDER_STEEL_SHAPE_SUCCESS";
export const GET_LIST_ORDER_STEEL_SHAPE_FAIL =
  "GET_LIST_ORDER_STEEL_SHAPE_FAIL";

export const POST_ORDER_STEEL_SHAPE = "POST_ORDER_STEEL_SHAPE";
export const POST_ORDER_STEEL_SHAPE_SUCCESS = "POST_ORDER_STEEL_SHAPE_SUCCESS";
export const POST_ORDER_STEEL_SHAPE_FAIL = "POST_ORDER_STEEL_SHAPE_FAIL";

export const FIND_LIST_ORDER_STEEL_SHAPE = "FIND_LIST_ORDER_STEEL_SHAPE";
export const FIND_LIST_ORDER_STEEL_SHAPE_SUCCESS =
  "FIND_LIST_ORDER_STEEL_SHAPE_SUCCESS";
export const FIND_LIST_ORDER_STEEL_SHAPE_FAIL =
  "FIND_LIST_ORDER_STEEL_SHAPE_FAIL";

export const DEL_LIST_ORDER_STEEL_SHAPE = "DEL_LIST_ORDER_STEEL_SHAPE";
export const DEL_LIST_ORDER_STEEL_SHAPE_SUCCESS =
  "DEL_LIST_ORDER_STEEL_SHAPE_SUCCESS";
export const DEL_LIST_ORDER_STEEL_SHAPE_FAIL =
  "DEL_LIST_ORDER_STEEL_SHAPE_FAIL";

export const GET_LIST_ORDER_STEEL_SHEET = "GET_LIST_ORDER_STEEL_SHEET";
export const GET_LIST_ORDER_STEEL_SHEET_SUCCESS =
  "GET_LIST_ORDER_STEEL_SHEET_SUCCESS";
export const GET_LIST_ORDER_STEEL_SHEET_FAIL =
  "GET_LIST_ORDER_STEEL_SHEET_FAIL";

export const FIND_LIST_ORDER_STEEL_SHEET = "FIND_LIST_ORDER_STEEL_SHEET";
export const FIND_LIST_ORDER_STEEL_SHEET_SUCCESS =
  "FIND_LIST_ORDER_STEEL_SHEET_SUCCESS";
export const FIND_LIST_ORDER_STEEL_SHEET_FAIL =
  "FIND_LIST_ORDER_STEEL_SHEET_FAIL";

export const POST_ORDER_STEEL_SHEET = "POST_ORDER_STEEL_SHEET";
export const POST_ORDER_STEEL_SHEET_SUCCESS = "POST_ORDER_STEEL_SHEET_SUCCESS";
export const POST_ORDER_STEEL_SHEET_FAIL = "POST_ORDER_STEEL_SHEET_FAIL";

export const DEL_LIST_ORDER_STEEL_SHEET = "DEL_LIST_ORDER_STEEL_SHEET";
export const DEL_LIST_ORDER_STEEL_SHEET_SUCCESS = "DEL_LIST_ORDER_STEEL_SHEET_SUCCESS";
export const DEL_LIST_ORDER_STEEL_SHEET_FAIL = "DEL_LIST_ORDER_STEEL_SHEET_FAIL";

export const GET_LIST_ORDER_BOLT = "GET_LIST_ORDER_BOLT";
export const GET_LIST_ORDER_BOLT_SUCCESS = "GET_LIST_ORDER_BOLT_SUCCESS";
export const GET_LIST_ORDER_BOLT_FAIL = "GET_LIST_ORDER_BOLT_FAIL";


export const POST_ORDER_BOLT = "POST_ORDER_BOLT";
export const POST_ORDER_BOLT_SUCCESS = "POST_ORDER_BOLT_SUCCESS";
export const POST_ORDER_BOLT_FAIL = "POST_ORDER_BOLT_FAIL";

export const FIND_LIST_ORDER_BOLT = "FIND_LIST_ORDER_BOLT";
export const FIND_LIST_ORDER_BOLT_SUCCESS = "FIND_LIST_ORDER_BOLT_SUCCESS";
export const FIND_LIST_ORDER_BOLT_FAIL = "FIND_LIST_ORDER_BOLT_FAIL";

export const DEL_LIST_ORDER_BOLT = "DEL_LIST_ORDER_BOLT";
export const DEL_LIST_ORDER_BOLT_SUCCESS = "DEL_LIST_ORDER_BOLT_SUCCESS";
export const DEL_LIST_ORDER_BOLT_FAIL = "DEL_LIST_ORDER_BOLT_FAIL";

export const GET_LIST_ORDER_OTHER = "GET_LIST_ORDER_OTHER";
export const GET_LIST_ORDER_OTHER_SUCCESS = "GET_LIST_ORDER_OTHER_SUCCESS";
export const GET_LIST_ORDER_OTHER_FAIL = "GET_LIST_ORDER_OTHER_FAIL";

export const POST_ORDER_OTHER = "POST_ORDER_OTHER";
export const POST_ORDER_OTHER_SUCCESS = "POST_ORDER_OTHER_SUCCESS";
export const POST_ORDER_OTHER_FAIL = "POST_ORDER_OTHER_FAIL";

export const FIND_LIST_ORDER_OTHER = "FIND_LIST_ORDER_OTHER";
export const FIND_LIST_ORDER_OTHER_SUCCESS = "FIND_LIST_ORDER_OTHER_SUCCESS";
export const FIND_LIST_ORDER_OTHER_FAIL = "FIND_LIST_ORDER_OTHER_FAIL";

export const DEL_LIST_ORDER_OTHER = "DEL_LIST_ORDER_OTHER";
export const DEL_LIST_ORDER_OTHER_SUCCESS = "DEL_LIST_ORDER_OTHER_SUCCESS";
export const DEL_LIST_ORDER_OTHER_FAIL = "DEL_LIST_ORDER_OTHER_FAIL";

//Product
export const GET_ALL_PRODUCT_COMMON_TYPE = "GET_ALL_PRODUCT_COMMON_TYPE";
export const GET_ALL_PRODUCT_COMMON_TYPE_SUCCESS =
  "GET_ALL_PRODUCT_COMMON_TYPE_SUCCESS";
export const GET_ALL_PRODUCT_COMMON_TYPE_FAIL =
  "GET_ALL_PRODUCT_COMMON_TYPE_FAIL";

export const GET_PRODUCT_CONSTRUCTION = "GET_PRODUCT_CONSTRUCTION";
export const GET_PRODUCT_CONSTRUCTION_SUCCESS =
  "GET_PRODUCT_CONSTRUCTION_SUCCESS";
export const GET_PRODUCT_CONSTRUCTION_FAIL = "GET_PRODUCT_CONSTRUCTION_FAIL";

export const POST_PRODUCT_CONSTRUCTION = "POST_PRODUCT_CONSTRUCTION";
export const POST_PRODUCT_CONSTRUCTION_SUCCESS =
  "POST_PRODUCT_CONSTRUCTION_SUCCESS";
export const POST_PRODUCT_CONSTRUCTION_FAIL = "POST_PRODUCT_CONSTRUCTION_FAIL";

export const PUT_PRODUCT_CONSTRUCTION = "PUT_PRODUCT_CONSTRUCTION";
export const PUT_PRODUCT_CONSTRUCTION_SUCCESS =
  "PUT_PRODUCT_CONSTRUCTION_SUCCESS";
export const PUT_PRODUCT_CONSTRUCTION_FAIL =
  "PUT_PRODUCT_CONSTRUCTION_SUCCESS_FAIL";

export const DEL_PRODUCT_CONSTRUCTION = "DEL_PRODUCT_CONSTRUCTION";
export const DEL_PRODUCT_CONSTRUCTION_SUCCESS =
  "DEL_PRODUCT_CONSTRUCTION_SUCCESS";
export const DEL_PRODUCT_CONSTRUCTION_FAIL = "DEL_PRODUCT_CONSTRUCTION_FAIL";

export const FIND_PRODUCT_CONSTRUCTION = "FIND_PRODUCT_CONSTRUCTION";
export const FIND_PRODUCT_CONSTRUCTION_SUCCESS =
  "FIND_PRODUCT_CONSTRUCTION_SUCCESS";
export const FIND_PRODUCT_CONSTRUCTION_FAIL = "FIND_PRODUCT_CONSTRUCTION_FAIL";
//Column
export const GET_COLUMN_COMPONENTS_PRODUCT = "GET_COLUMN_COMPONENTS_PRODUCT";
export const GET_COLUMN_COMPONENTS_PRODUCT_SUCCESS =
  "GET_COLUMN_COMPONENTS_PRODUCT_SUCCESS";
export const GET_COLUMN_COMPONENTS_PRODUCT_FAIL =
  "GET_COLUMN_COMPONENTS_PRODUCT_FAIL";

export const FIND_COLUMN_COMPONENTS_PRODUCT = "FIND_COLUMN_COMPONENTS_PRODUCT";
export const FIND_COLUMN_COMPONENTS_PRODUCT_SUCCESS =
  "FIND_COLUMN_COMPONENTS_PRODUCT_SUCCESS";
export const FIND_COLUMN_COMPONENTS_PRODUCT_FAIL =
  "FIND_COLUMN_COMPONENTS_PRODUCT_FAIL";

export const ADD_COLUMN_COMPONENTS_PRODUCT = "ADD_COLUMN_COMPONENTS_PRODUCT";
export const ADD_COLUMN_COMPONENTS_PRODUCT_SUCCESS =
  "ADD_COLUMN_COMPONENTS_PRODUCT_SUCCESS";
export const ADD_COLUMN_COMPONENTS_PRODUCT_FAIL =
  "ADD_COLUMN_COMPONENTS_PRODUCT_FAIL";

export const PUT_COLUMN_COMPONENTS_PRODUCT = "UPDATE_COLUMN_COMPONENTS_PRODUCT";
export const PUT_COLUMN_COMPONENTS_PRODUCT_SUCCESS =
  "UPDATE_COLUMN_COMPONENTS_PRODUCT_SUCCESS";
export const PUT_COLUMN_COMPONENTS_PRODUCT_FAIL =
  "UPDATE_COLUMN_COMPONENTS_PRODUCT_FAIL";

export const DEL_COLUMN_COMPONENTS_PRODUCT = "DEL_COLUMN_COMPONENTS_PRODUCT";
export const DEL_COLUMN_COMPONENTS_PRODUCT_SUCCESS =
  "DEL_COLUMN_COMPONENTS_PRODUCT_SUCCESS";
export const DEL_COLUMN_COMPONENTS_PRODUCT_FAIL =
  "DEL_COLUMN_COMPONENTS_PRODUCT_FAIL";

//Truss
export const GET_TRUSS_COMPONENTS_PRODUCT = "GET_TRUSS_COMPONENTS_PRODUCT";
export const GET_TRUSS_COMPONENTS_PRODUCT_SUCCESS =
  "GET_TRUSS_COMPONENTS_PRODUCT_SUCCESS";
export const GET_TRUSS_COMPONENTS_PRODUCT_FAIL =
  "GET_TRUSS_COMPONENTS_PRODUCT_FAIL";

export const FIND_TRUSS_COMPONENTS_PRODUCT = "FIND_TRUSS_COMPONENTS_PRODUCT";
export const FIND_TRUSS_COMPONENTS_PRODUCT_SUCCESS =
  "FIND_TRUSS_COMPONENTS_PRODUCT_SUCCESS";
export const FIND_TRUSS_COMPONENTS_PRODUCT_FAIL =
  "FIND_TRUSS_COMPONENTS_PRODUCT_FAIL";

export const DEL_TRUSS_COMPONENTS_PRODUCT = "DEL_TRUSS_COMPONENTS_PRODUCT";
export const DEL_TRUSS_COMPONENTS_PRODUCT_SUCCESS =
  "DEL_TRUSS_COMPONENTS_PRODUCT_SUCCESS";
export const DEL_TRUSS_COMPONENTS_PRODUCT_FAIL =
  "DEL_TRUSS_COMPONENTS_PRODUCT_FAIL";
//Main Girder
export const GET_MAIN_GIRDER_COMPONENTS_PRODUCT =
  "GET_MAIN_GIRDER_COMPONENTS_PRODUCT";
export const GET_MAIN_GIRDER_COMPONENTS_PRODUCT_SUCCESS =
  "GET_MAIN_GIRDER_COMPONENTS_PRODUCT_SUCCESS";
export const GET_MAIN_GIRDER_COMPONENTS_PRODUCT_FAIL =
  "GET_MAIN_GIRDER_COMPONENTS_PRODUCT_FAIL";

export const FIND_MAIN_GIRDER_COMPONENTS_PRODUCT =
  "FIND_MAIN_GIRDER_COMPONENTS_PRODUCT";
export const FIND_MAIN_GIRDER_COMPONENTS_PRODUCT_SUCCESS =
  "FIND_MAIN_GIRDER_COMPONENTS_PRODUCT_SUCCESS";
export const FIND_MAIN_GIRDER_COMPONENTS_PRODUCT_FAIL =
  "FIND_MAIN_GIRDER_COMPONENTS_PRODUCT_FAIL";

export const DEL_MAIN_GIRDER_COMPONENTS_PRODUCT =
  "DEL_MAIN_GIRDER_COMPONENTS_PRODUCT";
export const DEL_MAIN_GIRDER_COMPONENTS_PRODUCT_SUCCESS =
  "DEL_MAIN_GIRDER_COMPONENTS_PRODUCT_SUCCESS";
export const DEL_MAIN_GIRDER_COMPONENTS_PRODUCT_FAIL =
  "DEL_MAIN_GIRDER_COMPONENTS_PRODUCT_FAIL";
// export const DELETE_TRUSS_COLUMN_COMPONENTS_OF_PRODUCT = "DELETE_TRUSS_COLUMN_COMPONENTS_OF_PRODUCT";
// export const DELETE_TRUSS_COLUMN_COMPONENTS_OF_PRODUCT_SUCCESS = "DELETE_TRUSS_COLUMN_COMPONENTS_OF_PRODUCT_SUCCESS";
// export const DELETE_TRUSS_COLUMN_COMPONENTS_OF_PRODUCT_FAIL = "DELETE_TRUSS_COLUMN_COMPONENTS_OF_PRODUCT_FAIL";

// export const SEARCH__TRUSS_COLUMN_COMPONENTS_OF_PRODUCT = "SEARCH__TRUSS_COLUMN_COMPONENTS_OF_PRODUCT";
// export const SEARCH__TRUSS_COLUMN_COMPONENTS_OF_PRODUCT_SUCCESS = "SEARCH__TRUSS_COLUMN_COMPONENTS_OF_PRODUCT_SUCCESS";
// export const SEARCH__TRUSS_COLUMN_COMPONENTS_OF_PRODUCT_FAIL = "SEARCH__TRUSS_COLUMN_COMPONENTS_OF_PRODUCT_FAIL";
// Code layout
// product
export const GET_PRODUCT_CODE_LAYOUT = "GET_PRODUCT_CODE_LAYOUT";
export const GET_PRODUCT_CODE_LAYOUT_SUCCESS =
  "GET_PRODUCT_CODE_LAYOUT_SUCCESS";
export const GET_PRODUCT_CODE_LAYOUT_FAIL = "GET_PRODUCT_CODE_LAYOUT_FAIL";

//column
export const GET_COMPONENT_COLUMN_CODE_LAYOUT =
  "GET_COMPONENT_COLUMN_CODE_LAYOUT";
export const GET_COMPONENT_COLUMN_CODE_LAYOUT_SUCCESS =
  "GET_COMPONENT_COLUMN_CODE_LAYOUT_SUCCESS";
export const GET_COMPONENT_COLUMN_CODE_LAYOUT_FAIL =
  "GET_COMPONENT_COLUMN_CODE_LAYOUT_FAIL";

//truss
export const GET_COMPONENT_TRUSS_CODE_LAYOUT =
  "GET_COMPONENT_TRUSS_CODE_LAYOUT";
export const GET_COMPONENT_TRUSS_CODE_LAYOUT_SUCCESS =
  "GET_COMPONENT_TRUSS_CODE_LAYOUT_SUCCESS";
export const GET_COMPONENT_TRUSS_CODE_LAYOUT_FAIL =
  "GET_COMPONENT_TRUSS_CODE_LAYOUT_FAIL";
//main-girder
export const GET_COMPONENT_MAIN_GIRDER_CODE_LAYOUT =
  "GET_COMPONENT_MAIN_GIRDER_CODE_LAYOUT";
export const GET_COMPONENT_MAIN_GIRDER_CODE_LAYOUT_SUCCESS =
  "GET_COMPONENT_MAIN_GIRDER_CODE_LAYOUT_SUCCESS";
export const GET_COMPONENT_MAIN_GIRDER_CODE_LAYOUT_FAIL =
  "GET_COMPONENT_MAIN_GIRDER_CODE_LAYOUT_FAIL";

//Barcode
//Product
export const GET_BARCODE_PRODUCT = "GET_BARCODE_PRODUCT";
export const GET_BARCODE_PRODUCT_SUCCESS = "GET_BARCODE_PRODUCT_SUCCESS";
export const GET_BARCODE_PRODUCT_FAIL = "GET_BARCODE_PRODUCT_SUCCESS";

export const POST_EXPORT_BARCODE_PRODUCT = "POST_EXPORT_BARCODE_PRODUCT";
export const POST_EXPORT_BARCODE_PRODUCT_SUCCESS =
  "POST_EXPORT_BARCODE_PRODUCT_SUCCESS";
export const POST_EXPORT_BARCODE_PRODUCT_FAIL =
  "POST_EXPORT_BARCODE_PRODUCT_SUCCESS";
// column
export const GET_BARCODE_COLUMN = "GET_BARCODE_COLUMN";
export const GET_BARCODE_COLUMN_SUCCESS = "GET_BARCODE_COLUMN_SUCCESS";
export const GET_BARCODE_COLUMN_FAIL = "GET_BARCODE_COLUMN_FAIL";
//truss
export const GET_BARCODE_TRUSS = "GET_BARCODE_TRUSS";
export const GET_BARCODE_TRUSS_SUCCESS = "GET_BARCODE_TRUSS_SUCCESS";
export const GET_BARCODE_TRUSS_FAIL = "GET_BARCODE_TRUSS_FAIL";
//main-girder
export const GET_BARCODE_MAIN_GIRDER = "GET_BARCODE_MAIN_GIRDER";
export const GET_BARCODE_MAIN_GIRDER_SUCCESS =
  "GET_BARCODE_MAIN_GIRDER_SUCCESS";
export const GET_BARCODE_MAIN_GIRDER_FAIL = "GET_BARCODE_MAIN_GIRDER_FAIL";

export const POST_LIST_PRODUCT_INPUT = "POST_LIST_PRODUCT_INPUT";
export const POST_LIST_PRODUCT_INPUT_SUCCESS =
  "POST_LIST_PRODUCT_INPUT_SUCCESS";
export const POST_LIST_PRODUCT_INPUT_FAIL = "POST_LIST_PRODUCT_INPUT_FAIL";

// project management
export const GET_COMPANY_TRADING = "GET_COMPANY_TRADING";
export const GET_COMPANY_TRADING_SUCCESS = "GET_COMPANY_TRADING_SUCCESS";
export const GET_COMPANY_TRADING_FAIL = "GET_COMPANY_TRADING_FAIL";

export const GET_COMPANY_DESIGN = "GET_COMPANY_DESIGN";
export const GET_COMPANY_DESIGN_SUCCESS = "GET_COMPANY_DESIGN_SUCCESS";
export const GET_COMPANY_DESIGN_FAIL = "GET_COMPANY_DESIGN_FAIL";

export const GET_COMPANY_MANAGER = "GET_COMPANY_MANAGER";
export const GET_COMPANY_MANAGER_SUCCESS = "GET_COMPANY_MANAGER_SUCCESS";
export const GET_COMPANY_MANAGER_FAIL = "GET_COMPANY_MANAGER_FAIL";

export const GET_COMPANY_CONSTRUCTION = "GET_COMPANY_CONSTRUCTION";
export const GET_COMPANY_CONSTRUCTION_SUCCESS =
  "GET_COMPANY_CONSTRUCTION_SUCCESS";
export const GET_COMPANY_CONSTRUCTION_FAIL = "GET_COMPANY_CONSTRUCTION_FAIL";

export const GET_COMPANY_UT_REVIEW = "GET_COMPANY_UT_REVIEW";
export const GET_COMPANY_UT_REVIEW_SUCCESS = "GET_COMPANY_UT_REVIEW_SUCCESS";
export const GET_COMPANY_UT_REVIEW_FAIL = "GET_COMPANY_UT_REVIEW_FAIL";

export const GET_USER_EMPLOYEE = "GET_USER_EMPLOYEE";
export const GET_USER_EMPLOYEE_SUCCESS = "GET_USER_EMPLOYEE_SUCCESS";
export const GET_USER_EMPLOYEE_FAIL = "GET_USER_EMPLOYEE_FAIL";

export const GET_COMPANY_STAGE_ROUGHTING = "GET_COMPANY_STAGE_ROUGHTING";
export const GET_COMPANY_STAGE_ROUGHTING_SUCCESS =
  "GET_COMPANY_STAGE_ROUGHTING_SUCCESS";
export const GET_COMPANY_STAGE_ROUGHTING_FAIL =
  "GET_COMPANY_STAGE_ROUGHTING_FAIL";

export const GET_COMPANY_STAGE_PRODUCTION = "GET_COMPANY_STAGE_PRODUCTION";
export const GET_COMPANY_STAGE_PRODUCTION_SUCCESS =
  "GET_COMPANY_STAGE_PRODUCTION_SUCCESS";
export const GET_COMPANY_STAGE_PRODUCTION_FAIL =
  "GET_COMPANY_STAGE_PRODUCTION_FAIL";

//Sprint
//
export const GET_ALL_TYPE_STAGE_PROCESSING = "GET_ALL_TYPE_STAGE_PROCESSING";
export const GET_ALL_TYPE_STAGE_PROCESSING_SUCCESS =
  "GET_ALL_TYPE_STAGE_PROCESSING_SUCCESS";
export const GET_ALL_TYPE_STAGE_PROCESSING_FAIL =
  "GET_ALL_TYPE_STAGE_PROCESSING_FAIL";

//
export const GET_ALL_STAGES_PRODUCTION = "GET_ALL_STAGES_PRODUCTION";
export const GET_ALL_STAGES_PRODUCTION_SUCCESS =
  "GET_ALL_STAGES_PRODUCTION_SUCCESS";
export const GET_ALL_STAGES_PRODUCTION_FAIL = "GET_ALL_STAGES_PRODUCTION_FAIL";

//
export const POST_PRODUCTION_STAGE = "POST_PRODUCTION_STAGE";
export const POST_PRODUCTION_STAGE_SUCCESS = "POST_PRODUCTION_STAGE_SUCCESS";
export const POST_PRODUCTION_STAGE_FAIL = "POST_PRODUCTION_STAGE_FAIL";
// sprint
export const GET_ALL_STAGE_ROUGHING = "GET_ALL_STAGE_ROUGHING";
export const GET_ALL_STAGE_ROUGHING_SUCCESS = "GET_ALL_STAGE_ROUGHING_SUCCESS";
export const GET_ALL_STAGE_ROUGHING_FAIL = "GET_ALL_STAGE_ROUGHING_FAIL";

export const GET_ALL_STAGE_PRODUCTION = "GET_ALL_STAGE_PRODUCTION";
export const GET_ALL_STAGE_PRODUCTION_SUCCESS =
  "GET_ALL_STAGE_PRODUCTION_SUCCESS";
export const GET_ALL_STAGE_PRODUCTION_FAIL = "GET_ALL_STAGE_PRODUCTION_FAIL";

export const GET_PRODUCT_COMMON = "GET_PRODUCT_COMMON";
export const GET_PRODUCT_COMMON_SUCCESS = "GET_PRODUCT_COMMON_SUCCESS";
export const GET_PRODUCT_COMMON_FAIL = "GET_PRODUCT_COMMON_FAIL";

export const GET_ALL_STAGE_COMPONENT_TRUSS = "GET_ALL_STAGE_COMPONENT_TRUSS";
export const GET_ALL_STAGE_COMPONENT_TRUSS_SUCCESS =
  "GET_ALL_STAGE_COMPONENT_TRUSS_SUCCESS";
export const GET_ALL_STAGE_COMPONENT_TRUSS_FAIL =
  "GET_ALL_STAGE_COMPONENT_TRUSS_FAIL";

export const POST_STAGE_COMPONENT_TRUSS = "POST_STAGE_COMPONENT_TRUSS";
export const POST_STAGE_COMPONENT_TRUSS_SUCCESS =
  "POST_STAGE_COMPONENT_TRUSS_SUCCESS";
export const POST_STAGE_COMPONENT_TRUSS_FAIL =
  "POST_STAGE_COMPONENT_TRUSS_FAIL";
// process
export const GET_INFO_PRODUCT_BARCODE = "GET_INFO_PRODUCT_BARCODE";
export const GET_INFO_PRODUCT_BARCODE_SUCCESS =
  "GET_INFO_PRODUCT_BARCODE_SUCCESS";
export const GET_INFO_PRODUCT_BARCODE_FAIL = "GET_INFO_PRODUCT_BARCODE_FAIL";

export const GET_STAGE_ROUGHING = "GET_STAGE_ROUGHING";
export const GET_STAGE_ROUGHING_SUCCESS = "GET_STAGE_ROUGHING_SUCCESS";
export const GET_STAGE_ROUGHING_FAIL = "GET_STAGE_ROUGHING_FAIL";

export const POST_ROUGHING_STAGE = "POST_ROUGHING_STAGE";
export const POST_ROUGHING_STAGE_SUCCESS = "POST_ROUGHING_STAGE_SUCCESS";
export const POST_ROUGHING_STAGE_FAIL = "POST_ROUGHING_STAGE_FAIL";