const icons = {
  upic: require("../assets/icons/upic.png"),
  logo: require("../assets/icons/logo.svg"),
  icon_add: require("../assets/icons/icon-add.svg"),
  icon_delete: require("../assets/icons/icon-delete.svg"),
  icon_edit: require("../assets/icons/icon-edit.svg"),
  icon_print: require("../assets/icons/icon-print.svg"),
  icon_search: require("../assets/icons/icon-search.svg"),
  icon_previous: require("../assets/icons/icon-previous.svg"),
  icon_continuos: require("../assets/icons/icon-continuos.svg"),
  icon_process: require("../assets/icons/icon-menu-process.svg"),
  icon_manage: require("../assets/icons/icon-menu-manage.svg"),
  icon_storage: require("../assets/icons/icon-menu-storage.svg"),
  icon_fund: require("../assets/icons/icon-menu-fund.svg"),
  icon_staff: require("../assets/icons/icon-menu-staff.svg"),
  icon_find: require("../assets/icons/icon-find.svg"),
  icon_setting: require("../assets/icons/icon-setting.svg"),
  icon_noti: require("../assets/icons/icon-noti.svg"),
  icon_back: require("../assets/icons/icon-back.svg"),
  icon_plus: require("../assets/icons/icon-plus.svg"),
  icon_export_code: require("../assets/icons/icon-export-code.svg"),
  icon_layout_code: require("../assets/icons/icon-layout-code.svg"),
  icon_arrow_right: require("../assets/icons/icon-arrow-right.svg"),
  icon_arrow_left: require("../assets/icons/icon-arrow-left.svg"),
  icon_minimize: require("../assets/icons/icon-minimize.svg"),
  icon_maximize: require("../assets/icons/icon-maximize.svg"),
  icon_close_modal: require("../assets/icons/icon-close-modal.svg"),
  icon_arrow_up: require("../assets/icons/icon-arrow-up.svg"),
  icon_arrow_down: require("../assets/icons/icon-arrow-down.svg"),
  icon_calendar: require("../assets/icons/icon-calendar.svg"),
  icon_erase: require("../assets/icons/icon-erase.svg"),
  icon_pencil: require("../assets/icons/icon-pencil.svg"),
  icon_shift_left: require("../assets/icons/icon-shift-left.svg"),
  icon_shift_right: require("../assets/icons/icon-shift-right.svg"),
  icon_zoom_in: require("../assets/icons/icon-zoom-in.svg"),
  icon_zoom_out: require("../assets/icons/icon-zoom-out.svg"),
  icon_check_mark: require("../assets/icons/icon-check-mark.svg"),
  code_example: require("../assets/icons/code-example.svg"),
  logo_login: require("../assets/icons/logo-login.svg"),

};
export default icons;
